- name: Install MariaDB
  command: yum install mariadb-server -y

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Install MySQL-python
  yum:
    name: MySQL-python
    state: present

- name: Set MariaDB root password
  mysql_user:
    name: root
    password: '{{ mysql_root_password }}'
    login_user: root
    login_password: '{{ mysql_root_password }}'
    check_implicit_admin: yes
    priv: '*.*:ALL,GRANT'
    host: '{{ item }}'
  loop:
    - '{{ ansible_hostname }}'
    - 127.0.0.1
    - ::1
    - localhost
  
- name: Copy the root credentials as .my.cnf file
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600